sudo: required
language: haskell

before_install:
- mkdir -p $HOME/.local/bin; export PATH=$HOME/.local/bin:$PATH;
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack';
- travis_retry curl -L https://dist.ipfs.io/go-ipfs/v0.19.1/go-ipfs_v0.19.1_linux-amd64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/ipfs'
- ipfs init
- ipfs daemon &
- stack setup

install:
- echo nothing to install lol

script:
- stack -j2 --no-terminal --install-ghc test;

cache:
  directories:
  - $HOME/.stack