name:                ipfs-api
version:             0.1.0.0
github:              "f-o-a-m/ipfs-api"
license:             BSD3
author:              "Ilya Ostrovskiy"
maintainer:          "ilya@foam.space"
copyright:           "2018 Ilya Ostrovskiy"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/f-o-a-m/ipfs-api#readme>

dependencies:
- base
- aeson
- attoparsec 
- binary
- bytestring
- containers
- http-client
- http-media
- http-types
- ipld-cid
- servant 
- servant-client
- servant-client-core
- string-conversions
- text
- unordered-containers

default-extensions:
- DataKinds
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- LambdaCase
- MultiParamTypeClasses
- OverloadedStrings
- PolyKinds
- ScopedTypeVariables
- TypeApplications
- TypeFamilies
- TypeOperators

library:
  ghc-options:
  - -Werror
  source-dirs: src

executables:
  ipfs-api-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ipfs-api

tests:
  ipfs-api-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ipfs-api
    - hspec
    - hspec-contrib
    - hspec-discover
    - hspec-expectations
